# Generated by Django 5.0.6 on 2024-07-13 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_cat', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_cat', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id_con', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_con', models.CharField(max_length=255)),
                ('nombre_oficina_con', models.CharField(max_length=255)),
                ('sucursal_con', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id_cos', models.AutoField(primary_key=True, serialize=False)),
                ('c_costo_cos', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empre', models.AutoField(primary_key=True, serialize=False)),
                ('empresa_empre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id_pue', models.AutoField(primary_key=True, serialize=False)),
                ('puesto_pue', models.CharField(max_length=255)),
                ('calle_pue', models.CharField(max_length=255)),
                ('ciudad_pue', models.CharField(max_length=255)),
                ('provincia_pue', models.CharField(max_length=255)),
                ('fec_ingreso_pue', models.DateField()),
                ('fec_egreso_pue', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id_tra', models.AutoField(primary_key=True, serialize=False)),
                ('sucursal_tra', models.CharField(max_length=255)),
                ('departamento_tra', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('ci_emp', models.CharField(max_length=10)),
                ('legajo_emp', models.CharField(max_length=10)),
                ('apellido_emp', models.CharField(max_length=255)),
                ('nombre_emp', models.CharField(max_length=255)),
                ('religion_emp', models.CharField(blank=True, max_length=255, null=True)),
                ('t_doc_emp', models.CharField(max_length=255)),
                ('estado_civil_emp', models.CharField(max_length=255)),
                ('edad_emp', models.IntegerField()),
                ('fecha_nacimiento_emp', models.DateField()),
                ('nacionalidad_emp', models.CharField(max_length=255)),
                ('pais_emp', models.CharField(max_length=255)),
                ('provincia_emp', models.CharField(max_length=255)),
                ('localidad_emp', models.CharField(max_length=255)),
                ('genero_emp', models.CharField(max_length=255)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.puesto')),
            ],
        ),
    ]
